Flask Web/website/__init__.py
from flask import Flask, request, redirect
from flask_mysqldb import MySQL


mysql = MySQL()
def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'dseffs'
    app.config['MYSQL_HOST'] = 'localhost'
    app.config['MYSQL_USER'] = 'root'
    app.config['MYSQL_PASSWORD'] = 'RZ1mysql'
    app.config['MYSQL_DB'] = 'university'

    mysql.init_app(app)

    from .views import views
    #from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    #app.register_blueprint(auth, url_prefix='/')

    return app





Flask Web/website/auth.py
from flask import Blueprint

auth = Blueprint('auth', __name__)



Flask Web/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, flash
from . import mysql
from flask_mysqldb import MySQL

views = Blueprint('views', __name__)



@views.route('/')
def Student():
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM student")
    fetchdata = cur.fetchall()
    cur.close()
        
    return render_template("student1.html", students = fetchdata)




@views.route('/class')
def classes():
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM Course")
    fetchdata = cur.fetchall()
    cur.close()
        
    return render_template("class.html", classes = fetchdata)


@views.route('/teacher')
def teacher():
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM professor")
    fetchdata = cur.fetchall()
    cur.close()
    return render_template("teacher.html", professor = fetchdata)

@views.route('/dept')
def dept():
    return render_template("dept.html")


@views.route('/studentClass', methods = ['POST', 'GET'])
def studentClass():
    if request.method == 'POST':
        sID = request.form['sID']
        cur = mysql.connection.cursor()
        cur.execute("SELECT * FROM take Where StudentID=%s", (sID))
        classData = cur.fetchall()
        cur.close()
        return render_template("studentClass.html", studentClasses = classData)
    return render_template("studentClass.html")



@views.route('/insert', methods=['POST'])
def insert():
    if request.method == 'POST':
        flash('Data Inserted Successfully')
        sID = request.form['sID']
        Fname = request.form['Fname']
        Lname = request.form['Lname']
        address = request.form['address']
        major = request.form['major']

        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO student(StudentID, FirstName, LastName, Address, Major) VALUES (%s, %s, %s, %s, %s)", (sID, Fname, Lname, address, major))
        mysql.connection.commit()
        return redirect(url_for('views.Student'))


@views.route('/update', methods = ['POST', 'GET'])
def update():
    if request.method == 'POST':
        sID = request.form['sID']
        Fname = request.form['Fname']
        Lname = request.form['Lname']
        address = request.form['address']
        major = request.form['major']

        cur = mysql.connection.cursor()
        cur.execute("""
               UPDATE student
               SET FirstName=%s, LastName=%s, Address=%s, Major=%s
               WHERE StudentID=%s
            """, (Fname, Lname, address, major, sID))
        flash("Data Updated Successfully")
        mysql.connection.commit()
        return redirect(url_for('views.Student'))


@views.route('/delete/<string:id_data>', methods = ['POST', 'GET'])
def delete(id_data):
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM student WHERE StudentID=%s", (id_data,))
    mysql.connection.commit()
    return redirect(url_for('views.Student'))


@views.route('/insertSC', methods=['POST'])
def insertSC():
    if request.method == 'POST':
        flash('Data Inserted Successfully')
        sID = request.form['sID']
        cID = request.form['cID']
        grade = request.form['grade']


        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO take(StudentID, CourseID, Grade) VALUES (%s, %s, %s)", (sID, cID, grade))
        mysql.connection.commit()
        return redirect(url_for('views.studentClass'))


@views.route('/updateSC', methods = ['POST', 'GET'])
def updateSC():
    if request.method == 'POST':
        sID = request.form['sID']
        cID = request.form['cID']
        grade = request.form['grade']

        cur = mysql.connection.cursor()
        cur.execute("UPDATE take SET grade=%s WHERE StudentID=%s AND CourseID=%s", (grade, sID, cID))
        flash("Data Updated Successfully")
        mysql.connection.commit()
        return redirect(url_for('views.studentClass'))



@views.route('/deleteSC/<string:id_data>', methods = ['POST', 'GET'])
def deleteSC(id_data):
    IDs = id_data.split(' ')
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM take WHERE StudentID=%s AND CourseID=%s", (IDs[0],IDs[1]))
    mysql.connection.commit()
    return redirect(url_for('views.studentClass'))


@views.route('/updateC', methods = ['POST', 'GET'])
def updateC():
    if request.method == 'POST':
        cID = request.form['cID']
        Cname = request.form['Cname']
        credits = request.form['credits']
        prof = request.form['Pname']

        cur = mysql.connection.cursor()
        cur.execute("""
               UPDATE Course
               SET CourseID=%s, Title=%s, Credits=%s, ProfessorName=%s
               WHERE CourseID=%s
            """, (cID, Cname, credits, prof, cID))
        flash("Data Updated Successfully")
        mysql.connection.commit()
        return redirect(url_for('views.classes'))


@views.route('/insertC', methods=['POST'])
def insertC():
    if request.method == 'POST':
        flash('Data Inserted Successfully')
        cID = request.form['cID']
        Cname = request.form['Cname']
        credits = request.form['credits']
        prof = request.form['Pname']


        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO Course(CourseID, Title, Credits, ProfessorName) VALUES (%s, %s, %s, %s)", (cID, Cname, credits, prof))
        mysql.connection.commit()
        return redirect(url_for('views.classes'))

@views.route('/deleteC/<string:id_data>', methods = ['POST', 'GET'])
def deleteC(id_data):
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM Course WHERE CourseID=%s", (id_data,))
    mysql.connection.commit()
    return redirect(url_for('views.classes'))




    
@views.route('/updateT', methods = ['POST', 'GET'])
def updateT():
    if request.method == 'POST':
        Pname = request.form['Pname']
        dept = request.form['dept']
        email = request.form['email']

        cur = mysql.connection.cursor()
        cur.execute("""
               UPDATE professor
               SET ProfessorName=%s, Department=%s, Email=%s
               WHERE ProfessorName=%s
            """, (Pname, dept, email, Pname))
        flash("Data Updated Successfully")
        mysql.connection.commit()
        return redirect(url_for('views.teacher'))


@views.route('/insertT', methods=['POST'])
def insertT():
    if request.method == 'POST':
        flash('Data Inserted Successfully')
        Pname = request.form['Pname']
        dept = request.form['dept']
        email = request.form['email']

        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO professor(ProfessorName, Department, Email) VALUES (%s, %s, %s)", (Pname, dept, email))
        mysql.connection.commit()
        return redirect(url_for('views.teacher'))



@views.route('/deleteT/<string:id_data>', methods = ['POST', 'GET'])
def deleteT(id_data):
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM professor WHERE ProfessorName=%s", (id_data,))
    mysql.connection.commit()
    return redirect(url_for('views.teacher'))

Flask Web/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utfa-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />


    <title>{% block title %}Home{% endblock %}</title>
    </head>

    <body> 
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>

            </button>

            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" id="login" href="/">Student Data</a>
                    <a class="nav-item nav-link" id="stuClass" href="/studentClass">Student Class Data</a>
                    <a class="nav-item nav-link" id="signUp" href="/class">Class Data</a>
                    <a class="nav-item nav-link" id="logout" href="/teacher">Teacher Data</a>
                    <a class="nav-item nav-link" id="dept" href="/dept">Departments Data</a>
                </div>

            </div>
        </nav>
        
        <div class="container">
          {% block content %}

          {% endblock %}
        </div>

        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>
  
      <script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"
      ></script>  
      <script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>

      <script type="text/javascript" src="{{url_for('static', filename = 'js/bootstrap.min.js')}}"></script>
    </body>


</html>

Flask Web/website/templates/class.html
{% extends "base.html" %}

{% block title %}Classes{% endblock %}

{% block content %}
<h1>This is the classes page</h1>


<div class="container">
    <div class="row">
        <div class="col md-12">
        <h2>Class List <button type="button" class="btn btn-success pull-right" data-toggle = "modal" data-target="#mymodalC">Add Course Data</button></h2>
        {% with messages = get_flashed_messages() %}

        {% if messages %}

         {% for message in messages %}
         <div class="alert alert-success alert-dismissable" role="alert">

            <button type="button" class="close" data-dismiss="alert" aria-label="close" >
               <span aria-hidden="true">x</span>
            </button>
            {{message}}

         </div>


         {%endfor%}
         {%endif%}
         {%endwith%}

        <table class="table table-striped">
            <tr>
                <th>Course ID</th>
                <th>Title</th>
                <th>Credits</th>
                <th>Professor</th>
                <td>Action</td>

            </tr>

            {%for row in classes%}

            <tr>
                <td>{{row.0}}</td>
                <td>{{row.1}}</td>
                <td>{{row.2}}</td>
                <td>{{row.3}}</td>

                <td>
                    <a href="/updateC/{{row.0}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaleditC{{row.0}}">Edit</a> 
                    <a href="/deleteC/{{row.0}}" class="btn btn-danger btn-xd" onclick="return confirm('Are You Sure To Delete?')">Delete</a>

                </td>


            </tr>




    <div id="modaleditC{{row.0}}" class="modal fade" role="dialog">


        <div class="modal-dialog">
     
     
           <div class="modal-content">
     
     
              <div class="modal-header">
     
                <h4 class="modal-title">Please Edit Data</h4>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
     
     
     
              </div>
     
     
              <div class="modal-body">
     
     
                 <form action="{{url_for('views.updateC')}}" method="POST">


                  <div class="form-group">
     
     
                     <label>Course ID:</label>
                     <input type="text" class="form-control" name="cID" value="{{row.0}}">
   
   
                  </div>
     
     
                    <div class="form-group">
     
     
                       <label>Course Name:</label>
                       <input type="text" class="form-control" name="Cname" value="{{row.1}}">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Credits:</label>
                       <input type="text" class="form-control" name="credits" value="{{row.2}}">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Professor Name:</label>
                       <input type="text" class="form-control" name="Pname" value="{{row.3}}">
     
     
                    </div>
     
     
     
                    <div class="form-group">
     
     
                       <button class="btn btn-primary" type="submit">Update Data</button>
     
     
                    </div>
     
     
                 </form>
     
     
              </div>
  
     
              <div class="modal-footer">
     
     
                 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     
     
              </div>
     
     
           </div>
     
     
        </div>

    </div>

    {%endfor%}

   </table>


</div>

    <div id="mymodalC" class="modal fade" role="dialog">


        <div class="modal-dialog">
     
     
           <div class="modal-content">
     
     
              <div class="modal-header">
     
                <h4 class="modal-title">Please Insert Data</h4>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
     
     
     
              </div>
     
     
              <div class="modal-body">
     
     
                 <form action="{{url_for('views.insertC')}}" method="POST">
     
                    <div class="form-group">
     
     
                        <label>Course ID:</label>
                        <input type="text" class="form-control" name="cID" required="1">
      
      
                     </div>


                    <div class="form-group">
     
     
                       <label>Course Name:</label>
                       <input type="text" class="form-control" name="Cname" required="1">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Credits:</label>
                       <input type="text" class="form-control" name="credits" required="1">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Professor Name:</label>
                       <input type="text" class="form-control" name="Pname" required="1">
     
     
                    </div>
     
     
     
                    <div class="form-group">
     
     
                       <button class="btn btn-primary" type="submit">Insert Data</button>
     
     
                    </div>
     
     
                 </form>
     
     
              </div>
     
     
              <div class="modal-footer">
     
     
                 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     
     
              </div>
     
     
           </div>
     
     
        </div>
     

</div>

{% endblock %}

Flask Web/website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>This is the home page</h1>
{% endblock %}

Flask Web/website/templates/student1.html
{% extends "base.html" %}

{% block title %}Student Info{% endblock %}

{% block content %}

<h1 align="center">This is the student info page</h1>

<div class="container">
    <div class="row">
        <div class="col md-12">
        <h2>Student List <button type="button" class="btn btn-success pull-right" data-toggle = "modal" data-target="#myModal">Add Student Data</button></h2>
        {% with messages = get_flashed_messages() %}

        {% if messages %}

         {% for message in messages %}
         <div class="alert alert-success alert-dismissable" role="alert">

            <button type="button" class="close" data-dismiss="alert" aria-label="close" >
               <span aria-hidden="true">x</span>
            </button>
            {{message}}

         </div>


         {%endfor%}
         {%endif%}
         {%endwith%}

        <table class="table table-striped">
            <tr>
                <th>Student ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>Major</th>
                <td>Action</td>

            </tr>

            {%for row in students%}

            <tr>
                <td>{{row.0}}</td>
                <td>{{row.1}}</td>
                <td>{{row.2}}</td>
                <td>{{row.3}}</td>
                <td>{{row.4}}</td>
                <td>
                    <a href="/update/{{row.0}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.0}}">Edit</a> 
                    <a href="/delete/{{row.0}}" class="btn btn-danger btn-xd" onclick="return confirm('Are You Sure To Delete?')">Delete</a>

                </td>


            </tr>




    <div id="modaledit{{row.0}}" class="modal fade" role="dialog">


        <div class="modal-dialog">
     
     
           <div class="modal-content">
     
     
              <div class="modal-header">
     
                <h4 class="modal-title">Please Edit Data</h4>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
     
     
     
              </div>
     
     
              <div class="modal-body">
     
     
                 <form action="{{url_for('views.update')}}" method="POST">


                  <div class="form-group">
     
     
                     <label>Student ID:</label>
                     <input type="text" class="form-control" name="sID" value="{{row.0}}">
   
   
                  </div>
     
     
                    <div class="form-group">
     
     
                       <label>First Name:</label>
                       <input type="text" class="form-control" name="Fname" value="{{row.1}}">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Last Name:</label>
                       <input type="text" class="form-control" name="Lname" value="{{row.2}}">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Address:</label>
                       <input type="text" class="form-control" name="address" value="{{row.3}}">
     
     
                    </div>

                    <div class="form-group">
     
     
                        <label>Major:</label>
                        <input type="text" class="form-control" name="major" value="{{row.4}}">
      
      
                     </div>
     
     
     
                    <div class="form-group">
     
     
                       <button class="btn btn-primary" type="submit">Update Data</button>
     
     
                    </div>
     
     
                 </form>
     
     
              </div>
  
     
              <div class="modal-footer">
     
     
                 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     
     
              </div>
     
     
           </div>
     
     
        </div>

    </div>

    {%endfor%}

   </table>


</div>

    <div id="myModal" class="modal fade" role="dialog">


        <div class="modal-dialog">
     
     
           <div class="modal-content">
     
     
              <div class="modal-header">
     
                <h4 class="modal-title">Please Insert Data</h4>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
     
     
     
              </div>
     
     
              <div class="modal-body">
     
     
                 <form action="{{url_for('views.insert')}}" method="POST">
     
                    <div class="form-group">
     
     
                        <label>Studen ID:</label>
                        <input type="text" class="form-control" name="sID" required="1">
      
      
                     </div>


                    <div class="form-group">
     
     
                       <label>First Name:</label>
                       <input type="text" class="form-control" name="Fname" required="1">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Last Name:</label>
                       <input type="text" class="form-control" name="Lname" required="1">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Address:</label>
                       <input type="text" class="form-control" name="address" required="1">
     
     
                    </div>

                    <div class="form-group">
     
     
                        <label>Major:</label>
                        <input type="text" class="form-control" name="major" required="1">
      
      
                     </div>
     
     
     
                    <div class="form-group">
     
     
                       <button class="btn btn-primary" type="submit">Insert Data</button>
     
     
                    </div>
     
     
                 </form>
     
     
              </div>
     
     
              <div class="modal-footer">
     
     
                 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     
     
              </div>
     
     
           </div>
     
     
        </div>
     

</div>





{% endblock %}

Flask Web/website/templates/studentClass.html
{% extends "base.html" %}

{% block title %}Student Classes{% endblock %}
{% block content %}
<h1 align="center">This is the student info page</h1>


<form method="POST">
    <h3 align="center">Enter Student ID</h3>
    <div class="form-group">
        <label for="studentID">Student ID</label>
        <input type="text" class="form-control" name="sID" placeholder="Enter Student ID">
    
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>



<div class="container">
    <div class="row">
        <div class="col md-12">
        <h2>Student List <button type="button" class="btn btn-success pull-right" data-toggle = "modal" data-target="#classModal">Add Student Data</button></h2>
        {% with messages = get_flashed_messages() %}

        {% if messages %}

         {% for message in messages %}
         <div class="alert alert-success alert-dismissable" role="alert">

            <button type="button" class="close" data-dismiss="alert" aria-label="close" >
               <span aria-hidden="true">x</span>
            </button>
            {{message}}

         </div>


         {%endfor%}
         {%endif%}
         {%endwith%}

        <table class="table table-striped">
            <tr>
                <th>Student ID</th>
                <th>Class ID</th>
                <th>Grade</th>
                <td>Action</td>

            </tr>

            {%for row in studentClasses%}

            <tr>
                <td>{{row.0}}</td>
                <td>{{row.1}}</td>
                <td>{{row.2}}</td>
                <td>
                    <a href="/updateSC/{{row.0}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaleditSC{{row.0}}">Edit</a> 
                    <a href="/deleteSC/{{row.0 + ' ' +row.1}}" class="btn btn-danger btn-xd" onclick="return confirm('Are You Sure To Delete?')">Delete</a>

                </td>


            </tr>




    <div id="modaleditSC{{row.0}}" class="modal fade" role="dialog">


        <div class="modal-dialog">
     
     
           <div class="modal-content">
     
     
              <div class="modal-header">
     
                <h4 class="modal-title">Please Edit Data</h4>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
     
     
     
              </div>
     
     
              <div class="modal-body">
     
     
                 <form action="{{url_for('views.updateSC')}}" method="POST">


                  <div class="form-group">
     
     
                     <label>Student ID:</label>
                     <input type="text" class="form-control" name="sID" value="{{row.0}}">
   
   
                  </div>
     
     
                    <div class="form-group">
     
     
                       <label>Class ID:</label>
                       <input type="text" class="form-control" name="cID" value="{{row.1}}">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Grade:</label>
                       <input type="text" class="form-control" name="grade" value="{{row.2}}">
     
     
                    </div>
     
     
                
     
     
     
                    <div class="form-group">
     
     
                       <button class="btn btn-primary" type="submit">Update Data</button>
     
     
                    </div>
     
     
                 </form>
     
     
              </div>
  
     
              <div class="modal-footer">
     
     
                 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     
     
              </div>
     
     
           </div>
     
     
        </div>

    </div>

    {%endfor%}

   </table>


</div>

    <div id="classModal" class="modal fade" role="dialog">


        <div class="modal-dialog">
     
     
           <div class="modal-content">
     
     
              <div class="modal-header">
     
                <h4 class="modal-title">Please Insert Data</h4>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
     
     
     
              </div>
     
     
              <div class="modal-body">
     
     
                 <form action="{{url_for('views.insertSC')}}" method="POST">
     
                    <div class="form-group">
     
     
                        <label>Studen ID:</label>
                        <input type="text" class="form-control" name="sID" required="1">
      
      
                     </div>


                    <div class="form-group">
     
     
                       <label>Class ID:</label>
                       <input type="text" class="form-control" name="cID" required="1">
     
     
                    </div>
     
     
                     <div class="form-group">
     
     
                       <label>Grade:</label>
                       <input type="text" class="form-control" name="grade" required="1">
     
     
                    </div>
     
     
     
     
                    <div class="form-group">
     
     
                       <button class="btn btn-primary" type="submit">Insert Data</button>
     
     
                    </div>
     
     
                 </form>
     
     
              </div>
     
     
              <div class="modal-footer">
     
     
                 <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     
     
              </div>
     
     
           </div>
     
     
        </div>
     

</div>





{% endblock %}